import "./globals.css";
import GlobalProvider from "@/context/Context"; // Make sure the path is correct

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="montserrat-font">
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
